id: I11866BDE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T03:19:54+00:00'
last_modified: '2022-06-08T03:18:19.625378+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4951
  title: བསྐྱེད་རྫོགས་གནད་བསྡུས་ཀྱི་རྩ་འགྲེལ་ནོར་བུའི་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0B00:
      image_group_id: I3CN4953
      title: ''
      total_pages: 146
      order: 1
      base_file: 0B00.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
